# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cerge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for Cerge
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'


  pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'



  pod 'react-native-my-geo-location', :path => '../node_modules/react-native-my-geo-location'

end
