export const MAX_TIMEOUT = 10000; // 1000 = 1sec
export const FETCH_USER_DATA = 'FETCH_USER_DATA';

// COMMAN API CONSTANT
export const API_REQUEST = 'API_REQUEST';
export const API_FAILURE = 'API_FAILURE';

// AUTH API CONSTANT 
export const AUTH_API_REQUEST = 'AUTH_API_REQUEST';
export const AUTH_API_FAILURE = 'AUTH_API_FAILURE';
export const AUTH_LOGOUT_API_REQUEST = 'AUTH_LOGOUT_API_REQUEST';

//Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//LogOut
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//UPDATE PASSWORD
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';

//Forgot Password
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

//USER PROFILE VIEW
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PREFERENCES_SUCCESS = 'GET_USER_PREFERENCES_SUCCESS';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const GET_SYSTEM_CONFIG_SUCCESS = 'GET_SYSTEM_CONFIG_SUCCESS';

//Form data 
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';

// Update User Profile
export const PROFILE_API_REQUEST = 'PROFILE_API_REQUEST';
export const PROFILE_API_FAILURE = 'PROFILE_API_FAILURE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PREFERENCES_SUCCESS = 'UPDATE_USER_PREFERENCES_SUCCESS';

export const USER_PROFILE_IMAGE_SUCCESS = 'USER_PROFILE_IMAGE_SUCCESS';

//App Intor 
export const UPDATE_INTRO_STATUS = 'UPDATE_INTRO_STATUS';

// INVITATION API CONSTANT
export const INVITATION_API_REQUEST = 'INVITATION_API_REQUEST';
export const INVITATION_API_FAILURE = 'INVITATION_API_FAILURE';
export const INVITATION_LISTING = 'INVITATION_LISTING';
export const HIDE_RETAILER_INVITATION = 'HIDE_RETAILER_INVITATION';
export const ACCEPT_RETAILER__INVITATION = 'ACCEPT_RETAILER__INVITATION';
export const INVITATION_FILTER_LISTING = 'INVITATION_FILTER_LISTING';

export const INVITATION_DETAIL_REQUEST = 'INVITATION_DETAIL_REQUEST';
export const INVITATION_DETAIL_FAILURE = 'INVITATION_DETAIL_FAILURE';
export const INVITATION_DETAIL = 'INVITATION_DETAIL';
export const HIDE_INVITATION_FROM_REMOVED = 'HIDE_INVITATION_FROM_REMOVED';
export const LOADER_SHOW_HIDE = 'LOADER_SHOW_HIDE';
export const INVITATION_FILTER_REQUEST_CLEAR = 'INVITATION_FILTER_REQUEST_CLEAR';

//Common API constant
export const COMMON_API_REQUEST = 'COMMON_API_REQUEST';
export const COMMON_API_FAILURE = 'COMMON_API_FAILURE';
export const FETCH_STORE_DATA = 'FETCH_STORE_DATA';
export const ENTER_STORE = 'ENTER_STORE';
export const LEAVE_STORE = 'LEAVE_STORE';
export const SET_NEAR_STORE = 'SET_NEAR_STORE';
export const SET_OUT_STORE = 'SET_OUT_STORE';
export const RESET_PING = 'RESET_PING';

// SHOPPING API CONSTANT
export const SHOPPING_API_REQUEST = 'SHOPPING_API_REQUEST';
export const SHOPPING_API_FAILURE = 'SHOPPING_API_FAILURE';
export const SHOPPING_UPDATE = 'SHOPPING_UPDATE';

// RETAILER API CONSTANT
export const RETAILER_API_REQUEST = 'RETAILER_API_REQUEST';
export const RETAILER_API_FAILURE = 'RETAILER_API_FAILURE';
export const ACCEPTED_RETAILER_LISTING = 'ACCEPTED_RETAILER_LISTING';
export const REMOVED_RETAILER_LISTING = 'REMOVED_RETAILER_LISTING';
export const HIDE_RETAILER_FROM_REMOVED = 'HIDE_RETAILER_FROM_REMOVED';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const UPDATE_RETAILER_LOYALTY = 'UPDATE_RETAILER_LOYALTY';

// REVIEW API CONSTANT
export const REVIEW_API_REQUEST = 'REVIEW_API_REQUEST';
export const REVIEW_API_FAILURE = 'REVIEW_API_FAILURE';
export const REVIEW_HISTORY_LISTING = 'REVIEW_HISTORY_LISTING';
export const REVIEW_RATING = 'REVIEW_RATING';
export const REVIEW_API_LOADMORE = 'REVIEW_API_LOADMORE';
export const REVIEW_HISTORY_LISTING_MOREDATA = 'REVIEW_HISTORY_LISTING_MOREDATA';
export const REVIEW_API_PULLTOREFRESH = 'REVIEW_API_PULLTOREFRESH';
export const REQUESTDATA = 'REQUESTDATA';
export const UPDATE_LOADMORE_REQUEST = 'UPDATE_LOADMORE_REQUEST';

//Status
export const SHOPPING = 'On a mission';
export const BROWSING = 'Perusing';
export const DND = 'Do not disturb';
export const ASSISTANCE = 'Require assistance';

export const SHOPPINGLABEL = 'On a mission';
export const BROWSINGLABEL = 'Perusing';
export const DNDLABEL = 'DND';
export const ASSISTANCELABEL = 'Require assistance';
