export const LABELS = {
  SLIDE_TITLE:
    'Cérge is your Click and Collect Concierge supporting contactless shopping.',
  SLIDE_TEXT:
    'How Cérge works\n\n1. Enter your info into the Cérge app\n2. Choose which businesses you trust\n3. Cérge introduces you to the retailer the moment you walk in the door\n4. You are always in control of the data you hand over.',
  PROJECT_NAME: 'Cerge',
  USERNAME: 'HELLO',
  SHOPPING_RATING_SUB_TITLE: 'What is your status?',
  RATING_HEADING: 'Rate your experience at \n',
  SUBMIT_RATING: 'SUBMIT RATING',
  SAVE: 'SAVE',
  NOT_NOW: 'NOT NOW',
  REVIEW_SUB_TITLE: 'Rate your businesses',
  DATE: 'DATE',
  WALKED_IN: 'WALKED IN',
  WALKED_OUT: 'WALKED OUT',
  RATING: 'RATING',
  RATE: 'RATE',
  DATA_EXCHANGED: 'Data exchanged',
  INVITATION_RECIEVED: 'Invitation received',
  SHARE: 'SHARE',
  INVITATION_SUBTITLE: 'Showing businesses',
  INVITATION_LINK_TEXT: 'near me',
  INVITATION_HEADING: 'Businesses offering\ncontactless service',
  HATNAME_SUBTITIME: 'Please enter you HAT name',
  WELCOME: 'WELCOME',
  HATNAME_LABEL: 'Your HAT name',
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  LOGIN_SUBTITLE: 'Please enter your details',
  EMAIL_LABEL: 'Your email',
  NEXT: 'NEXT',
  SKIP: 'SKIP',
  GETSTARTED: 'GET STARTED',
  CAMERA_PERMISSION:
    'Permission to access your Camera and Photo is disabled. Please allow from application permission.',
  PERMISSION: 'We need your permission.',
  NAME_LABEL: 'Your name',
  DOB_SELECT: 'Select Date of Birth',
  UPDATE_PROFILE: 'Submit',
  FIND_TRUSTED_RETAILERS: 'FIND TRUSTED BUSINESSES',
  ENTER_CLOTHING_SIZES: 'COMPLETE YOUR PROFILE',
  YOUR_PROFIE: 'YOUR PROFILE',
  PROFILE_SUBTITLE: 'Please fill out your details',
  UPLOAD_PROFILE_PIC: 'UPLOAD PROFILE PHOTO',
    SHOPPING: 'On a mission',
    BROWSING: 'Perusing',
    DND: 'Do not disturb',
  ASSISTANCE: 'Require assistance',
  FROMTIME: 'I am on a mission between',
  TOTIME: 'I am on a mission between',
  SHOPPING_FOR: 'I am on a mission to',
  SHOPPING_FOR_PLACEHOLDER: 'Enter essential items you are looking for',
  ON: 'On',
  OR: 'or',
  INVITATION_ACCEPT_SUBTITLE: 'Your offer has been added to your businesses',
  YES_SIGNUP: 'YES, SIGN-UP',
  NO_THANKS: 'NO THANKS',
  LOYALTY_LABEL: 'Enter loyalty number',
  LOYALTY_SIGNUP_TEXTINITIAL: 'Would you like to sign-up and\n become a',
  LOYALTY_SIGNUP_TEXTFINISH: '\n loyalty VIP',
  SEARCH_INVITATIONS: 'SEARCH INVITATIONS',
  SEARCH_INVITATIONS_SUBTITLE: 'What are you looking for?',
  AT_THIS_PLACE: 'At this place',
  AT_THIS_PLACE_PLACEHOLDER: 'Emporium Melbourne',
  ACCEPTED_RETAILERS: 'Showing trusted businesses',
  REMOVED_RETAILERS: 'Showing blocked businesses',
    EMAIL_LINK_TEXT: 'report a bug',
  ADD_RETAILER: 'Add Business',
  REMOVE_RETAILER: 'Block Business',
  HIDE_RETAILER: 'Hide Business',
  VIP_PREMIUM: 'VIP premium experience',
  MORE_INFO: 'MORE INFO',
  TENPERCENT_DISCOUNT: '10% discount off all stock',
  LOYALTY_NUMBER_TEXT: 'Loyalty #:',
  DATA_PRIVACY_TEXT: 'data privacy statement',
  INFO: 'INFORMATION: ',
  INFO_DESC: 'These offers are exchanged for data from my data account.',
  ACCEPT_INVITATION: 'ACCEPT INVITATION',
  METER_FROM_YOU: ' from you',
  SEARCH_NEAR_ME: 'or search near me',
  NO_RATING: 'No Rating found.',
  NO_INVITATIONS: 'No invitations found.',
  NO_RETAILERS: 'No Businesses found.',
  MY_PREFRENCES: 'MY PREFRENCES',
  PLEASE_WAIT: 'Please wait...',
  LOYALTY_NUMBER: 'Loyalty no.'
};
